### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by SkyeMors** [1010101110/ValheimMods#10]
Log is continually spammed just about every frame with the following:

[Error  : Unity Log] MissingMethodException: StatusEffect SEMan.AddStatusEffect(string,bool)
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::FixedUpdate>(Player)

With my VERY limited work with making things in Unity, I can only assume that using a FixedUpdate for a Status Effect isn't ideal, especially if it's a Status Effect that's broken like this that'll spam the log with the error every activation (every FixedUpdate, or effectively in-engine tick).

![image](https://user-images.githubusercontent.com/39830646/208224808-69256a58-cc3c-483a-a222-06ea18093795.png)

**Comment by 1010101110** [comment]
which mod are you using?
@SkyeMors

**Comment by SkyeMors** [comment]
the mushrooms one

**Comment by SkyeMors** [comment]
Good news, the log is no longer spammed after the mod was updated.
