### ISSUE TITLE
Error on Shrooms

### ISSUE THREAD

**Issue by The-Bees-Decree-Server** [1010101110/ValheimMods#12]
[Error  : Unity Log] MissingMethodException: StatusEffect SEMan.GetStatusEffect(string)
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::FixedUpdate>(Player)

Likely needs updating after last patch.

**Comment by 1010101110** [comment]
fixed in 1.1.3

**Comment by The-Bees-Decree-Server** [comment]
Awesome thank you!
