### ISSUE TITLE
 can't assign names on portal with the latest 148.6

### ISSUE THREAD

**Issue by quentfr21** [1010101110/ValheimMods#2]
when you press "e" to assign names on portal the dialog popup won't show up
no conflict in keyborad config
after remove multiverse it's work fine 

thanks in advance

**Comment by 1010101110** [comment]
what other mods do you have running

**Comment by 1010101110** [comment]
oh latest update broke portals code? maybe they changed portal stuff.

**Comment by FearghusMcMahon** [comment]
[Error  : Unity Log] MissingMethodException: bool PrivateArea.CheckAccess(UnityEngine.Vector3,single,bool)
Stack trace:
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::Interact>(TeleportWorld,Humanoid,bool)
Player.Interact (UnityEngine.GameObject go, System.Boolean hold) (at <8c7c34821ea14feca71b1c03f25447d0>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

Client log gives the above error.

**Comment by 1010101110** [comment]
thank you @FearghusMcMahon 

they changed the method signature for this patch

**Comment by pipakin** [comment]
Yeah they just added a fourth optional param to PrivateArea.CheckAccess

You can honestly probably just recompile against the new binaries.

**Comment by 1010101110** [comment]
yea why does it throw an error if its defaulted

**Comment by pipakin** [comment]
Right? Some weird crap right there.
