### ISSUE TITLE
cant get mod to work?

### ISSUE THREAD

**Issue by truffulatreez** [1010101110/ValheimMods#3]
Hi there, im hosting 2 separate dedicated servers.  they both have passwords but valheim+ is set to ignore passwords.  here are my two portal tags (my IPs are omitted for privacy)

JeebieWeebieStation|111.11.111.111:22222|stinky
BigVibesAnonymous|11.111.11.111:22222|truffle

any idea why the portals are not connecting?  I have the .dll correctly stored in the plugins folder along with many other working mods.  i have also tried making the tags not inclue the password section, along with a few other combinations i thought might work.  so far no amount of tweaking has managed to connect the portals

**Comment by 1010101110** [comment]
i do not have any experience with v+ if it is patching some functionality that i am and overriding it.

you might look in your bepinex log and see if there are errors or what.

so you set the text then just nothing happens? can you walk through them and get a message?

**Comment by truffulatreez** [comment]
yeah i set both tags and then nothing happens, i dont notice any red messages from bepinex either.  i also have about 20 other nexus mods running client side, with valhiem+ and the server both being hosted on gportal.com
