### ISSUE TITLE
Can't get portals to connect locally

### ISSUE THREAD

**Issue by yndrelbosch** [1010101110/ValheimMods#4]
As the title says, I can't get the portals to connect to local worlds. I have two worlds I'm trying to connect, Fimbull and Vallar, so I first typed in `World|Fimbull` into the portal on the Vallar side, and `World|Vallar` into the portal on the Fimbull side. That didn't work, so I thought, maybe capitalization matters, so I tried both `world|Fimbull` and `world|Vallar` and `world|fimbull` and `world|vallar` to no avail. I even tried launching a server to see if that did anything, but naughta. Any suggestions / ideas?

**Comment by 1010101110** [comment]
do you see any errors in your bepinex log?

**Comment by yndrelbosch** [comment]
Apologies for not getting back right away, I actually found out the issue, it was an incompatibility with another Portal mod I had installed that allowed portals to go to any destination.
