### ISSUE TITLE
Would an update for Hearth and Home be possible?

### ISSUE THREAD

**Issue by RocketRaccoon7** [1010101110/ValheimMods#7]
I was wondering if you could update this plugin for hearth and home? When it returns to the base menu to load into the second world after entering a multiverse portal it now just dies and stays stuck on the main menu screen. Our servers really loved your plugin.

**Comment by 1010101110** [comment]
sure, i'll test it out later today

**Comment by RocketRaccoon7** [comment]
My apologies for ghosting there, life came up, I did get an error. Right at the end you can even see the process where it starts to log out the character and begin the process of logging into the next server before it errors.

What I see in game is its normal drop back to the main menu, but then it never seems to make it to logging into the second server. Here's what the error looks like in BepInEx:

[Info   : Unity Log] 11/24/2021 03:17:30: Minimap: Adding unique location (5.1, 82.5, -192.7)
[Info   : Unity Log] 11/24/2021 03:17:30: Minimap: Adding unique location (-1233.0, 40.9, 962.2)
[Info   :Better Wards] Server has Better Wards installed
[Info   : Unity Log] 11/24/2021 03:17:35: client got keys 6
[Info   : Unity Log] 11/24/2021 03:17:36: TRIGGER
[Info   : Unity Log] 11/24/2021 03:17:36: Teleporting Joël
[Info   : Unity Log] 11/24/2021 03:17:56: TRIGGER
[Info   : Unity Log] 11/24/2021 03:17:56: Teleporting Joël
[Warning: Unity Log] 11/24/2021 03:17:56: Multiverse - logging out and connecting to: 64.*.*.* (I starred my ip out):2459
[Info   : Unity Log] 11/24/2021 03:17:56: Shuting down
[Info   : Unity Log] 11/24/2021 03:17:56: Uncompressed size 8395178
[Info   : Unity Log] 11/24/2021 03:17:56: Compressed size 20455
[Info   : Unity Log] 11/24/2021 03:17:56: ZNet Shutdown
[Info   : Unity Log] 11/24/2021 03:17:56: Sending disconnect msg
[Info   : Unity Log] 11/24/2021 03:17:56: Sent to 90152925381170177
[Info   : Unity Log] 11/24/2021 03:17:56: Released session ticket
[Info   : Unity Log] 11/24/2021 03:17:56: Disposing socket
[Info   : Unity Log] 11/24/2021 03:17:56: Closing socket 90152925381170177
[Info   : Unity Log] 11/24/2021 03:17:56:   send queue size:0
[Info   : Unity Log] 11/24/2021 03:17:56: Last socket, unregistering callback
[Info   : Unity Log] 11/24/2021 03:17:56: ZSteamSocket  UnregisterGlobalCallbacks, existing sockets:0
[Info   : Unity Log] 11/24/2021 03:17:56: Disposing socket
[Info   : Unity Log] 11/24/2021 03:17:56: Last socket, unregistering callback
[Info   : Unity Log] 11/24/2021 03:17:56: ZSteamSocket  UnregisterGlobalCallbacks, existing sockets:0
[Warning: Unity Log] 11/24/2021 03:17:56: Local player destroyed
[Info   : Unity Log] 11/24/2021 03:17:57: ZNet OnDestroy
[Info   : Unity Log] 11/24/2021 03:17:57: Net scene destroyed
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 11/24/2021 03:17:57: Valheim version:0.204.4
[Info   :Jotunn.Managers.CommandManager] Adding 1 commands to the Console
[Info   : Unity Log] 11/24/2021 03:17:57: Render threading mode:MultiThreaded
[Info   : Unity Log] 11/24/2021 03:17:57: Steam initialized, persona:Rocket_Co
[Info   : Unity Log] 11/24/2021 03:17:57: Audioman already exist, destroying self
[Info   : Unity Log] 11/24/2021 03:17:57: Checking for installed DLCs
[Info   : Unity Log] 11/24/2021 03:17:57: DLC:beta installed:True
[Info   : Unity Log] CustomTextures Clutter system awake
[Info   : Unity Log] CustomTextures Checking 17 clutters
[Info   : Unity Log] CustomTextures Clutter System RunTime 00:00:00.00
[Info   :Jotunn.Managers.LocalizationManager] Loading custom localizations
[Warning:Jotunn.Managers.LocalizationManager] Localization (com.jotunn.jotunn) already added
[Info   : Unity Log] 11/24/2021 03:17:58: Loaded localization CSV:localization language:English
[Info   : Unity Log] 11/24/2021 03:17:58: Loaded localization CSV:localization_extra language:English
[Info   :Jotunn.Managers.LocalizationManager] Adding tokens for language 'English'
[Info   :Jotunn.Managers.ItemManager] Adding 1 custom items to the ObjectDB
[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.GameObject.GetComponent[T] () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
EpicLoot.EpicLoot+<>c.<TryRegisterItems>b__78_0 (UnityEngine.GameObject x) (at <1cba68a8febf45b3a8829a7f8276a41b>:0)
System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.List`1[T].InsertRange (System.Int32 index, System.Collections.Generic.IEnumerable`1[T] collection) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.List`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] collection) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
EpicLoot.EpicLoot.TryRegisterItems () (at <1cba68a8febf45b3a8829a7f8276a41b>:0)
EpicLoot.ObjectDB_CopyOtherDB_Patch.Postfix () (at <1cba68a8febf45b3a8829a7f8276a41b>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::CopyOtherDB>(ObjectDB,ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::CopyOtherDB>?-384655360(ObjectDB,ObjectDB)
Jotunn.Managers.ItemManager.RegisterCustomDataFejd (On.ObjectDB+orig_CopyOtherDB orig, ObjectDB self, ObjectDB other) (at <c78153f1de6d4eb1b54dd9c6030d7f58>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::CopyOtherDB>?1173338112(ObjectDB,ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::CopyOtherDB>?-1933877248(ObjectDB,ObjectDB)
Jotunn.Managers.PrefabManager.InvokeOnVanillaObjectsAvailable (On.ObjectDB+orig_CopyOtherDB orig, ObjectDB self, ObjectDB other) (at <c78153f1de6d4eb1b54dd9c6030d7f58>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::CopyOtherDB>?594939648(ObjectDB,ObjectDB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<ObjectDB::CopyOtherDB>?-237034496(ObjectDB,ObjectDB)
Jotunn.Managers.ItemManager.InvokeOnItemsRegisteredFejd (On.ObjectDB+orig_CopyOtherDB orig, ObjectDB self, ObjectDB other) (at <c78153f1de6d4eb1b54dd9c6030d7f58>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<ObjectDB::CopyOtherDB>?-1877877888(ObjectDB,ObjectDB)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::SetupObjectDB>(FejdStartup)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)
[Info   : Unity Log] 11/24/2021 03:17:58: UI Group status changed Menu = True
[Info   : Unity Log] 11/24/2021 03:18:00: UI Group status changed Menu = True
[Error  : Unity Log] ArgumentException: Mesh can not have more than 65000 vertices
Stack trace:
UnityEngine.UI.VertexHelper.FillMesh (UnityEngine.Mesh mesh) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Graphic.DoMeshGeneration () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Graphic.UpdateGeometry () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Text.UpdateGeometry () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.Canvas:SendWillRenderCanvases()
