### ISSUE TITLE
Error with CandlesLanternsANDBeeswax

### ISSUE THREAD

**Issue by norby007** [1010101110/ValheimMods#8]
Any ideas on how to fix this?

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Jotunn.Entities.CustomPiece..ctor (UnityEngine.GameObject piecePrefab, System.String pieceTable, System.Boolean fixReference) (at <6755f0d8dbee46868937bcd835f27a73>:0)
MagikarpCandles.CandlesLanternsANDBeeswax.LoadItems () (at <6c9d54ab558f4f3e86ec2c66180cd56c>:0)
MagikarpCandles.CandlesLanternsANDBeeswax.Awake () (at <6c9d54ab558f4f3e86ec2c66180cd56c>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by 1010101110** [comment]
yeah i probably removed one of the prefabs without removing the reference to it.

the reason i did that is because skull candle is causing a duplication loop that will crash an area. but yeah i should fix that someday.

**Comment by norby007** [comment]
cool, as long as it does not cause stability issues it should be okay. thanks for fixing the beeswax :)
