### ISSUE TITLE
No documentation on increasing Name limit of portals

### ISSUE THREAD

**Issue by NiemandNatural** [1010101110/ValheimMods#9]
Sers!

Portal names are limited to ~10 letters. Getting IPs in there is not feasable.

No documentation for the mod on how to solve that.
No response to my request in mod-thread on nexusmods 2 months ago.

Plz help!

**Comment by 1010101110** [comment]
the limit was removed in the mod, is there are a bug with that?

**Comment by NiemandNatural** [comment]
Could you add that info to the mod description? (Sorry if it's there but I read over it.)

When I installed the mod in February, the limit was still active. I couldn't test if this was a mod bug or if the mod itself didn't work (no error-messages came to my eyes or I would have reported those) - as the limits didn't get removed.
It seems I wasn't the only one, see nexusmods mod thread post #78 (my post is #80, I think).

At the moment, I couldn't test it because I seem to have to reinstall my valheim-server (again -.-), as updating doesn't seem to work properly with umod (or I am making mistakes).
I will reinstall it and send you my results regarding your mod. Feel free to try and reproduce/fix it, though. :)
